# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1398, 659)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background:qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(29, 51, 98, 255), stop:1 rgba(9, 23, 58, 255))")
        self.open_button = QtWidgets.QPushButton(Dialog)
        self.open_button.setGeometry(QtCore.QRect(50, 590, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.open_button.setFont(font)
        self.open_button.setStyleSheet("font-size:15px;\n"
"font-style:\"Inter\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.open_button.setObjectName("open_button")
        self.line_button = QtWidgets.QPushButton(Dialog)
        self.line_button.setGeometry(QtCore.QRect(220, 590, 120, 40))
        self.line_button.setStyleSheet("font-size:15px;\n"
"font-style:\"Inter\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.line_button.setObjectName("line_button")
        self.start_button = QtWidgets.QPushButton(Dialog)
        self.start_button.setGeometry(QtCore.QRect(390, 590, 120, 40))
        self.start_button.setStyleSheet("font-size:15px;\n"
"font-style:\"Inter\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.start_button.setObjectName("start_button")
        self.pause_button = QtWidgets.QPushButton(Dialog)
        self.pause_button.setGeometry(QtCore.QRect(550, 590, 111, 41))
        self.pause_button.setStyleSheet("font-size:15px;\n"
"font-style:\"Inter\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pause_button.setObjectName("pause_button")
        self.count = QtWidgets.QGroupBox(Dialog)
        self.count.setGeometry(QtCore.QRect(860, 10, 511, 611))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.count.setFont(font)
        self.count.setStyleSheet("color:white;\n"
"")
        self.count.setObjectName("count")
        self.Car = QtWidgets.QLabel(self.count)
        self.Car.setGeometry(QtCore.QRect(100, 50, 51, 21))
        self.Car.setStyleSheet("background:None")
        self.Car.setAlignment(QtCore.Qt.AlignCenter)
        self.Car.setObjectName("Car")
        self.Bus = QtWidgets.QLabel(self.count)
        self.Bus.setGeometry(QtCore.QRect(270, 50, 51, 21))
        self.Bus.setStyleSheet("background:None")
        self.Bus.setAlignment(QtCore.Qt.AlignCenter)
        self.Bus.setObjectName("Bus")
        self.Truck = QtWidgets.QLabel(self.count)
        self.Truck.setGeometry(QtCore.QRect(360, 50, 51, 21))
        self.Truck.setStyleSheet("background:None")
        self.Truck.setAlignment(QtCore.Qt.AlignCenter)
        self.Truck.setObjectName("Truck")
        self.Minibus = QtWidgets.QLabel(self.count)
        self.Minibus.setGeometry(QtCore.QRect(180, 50, 61, 21))
        self.Minibus.setStyleSheet("background:None")
        self.Minibus.setAlignment(QtCore.Qt.AlignCenter)
        self.Minibus.setObjectName("Minibus")
        self.Sum = QtWidgets.QLabel(self.count)
        self.Sum.setGeometry(QtCore.QRect(440, 50, 61, 21))
        self.Sum.setStyleSheet("background:None")
        self.Sum.setAlignment(QtCore.Qt.AlignCenter)
        self.Sum.setObjectName("Sum")

        self.image = QtWidgets.QLabel(Dialog)
        self.image.setGeometry(QtCore.QRect(30, 90, 800, 450))
        self.image.setStyleSheet("background:none;")
        self.image.setText("")
        self.image.setObjectName("image")
        self.expert_button = QtWidgets.QPushButton(Dialog)
        self.expert_button.setGeometry(QtCore.QRect(700, 590, 111, 41))
        self.expert_button.setStyleSheet("font-size:15px;\n"
"font-style:\"Inter\";\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.expert_button.setObjectName("expert_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.open_button.setText(_translate("Dialog", "Open Video"))
        self.line_button.setText(_translate("Dialog", "Select Area"))
        self.start_button.setText(_translate("Dialog", "Start"))
        self.pause_button.setText(_translate("Dialog", "Pause"))
        self.count.setTitle(_translate("Dialog", "Counting Results"))
        self.Car.setText(_translate("Dialog", "Car"))
        self.Bus.setText(_translate("Dialog", "Bus"))
        self.Truck.setText(_translate("Dialog", "Truck"))
        self.Minibus.setText(_translate("Dialog", "Minibus"))
        self.Sum.setText(_translate("Dialog", "Sum"))
        self.expert_button.setText(_translate("Dialog", "Export"))
